### ISSUE TITLE
Put signs closer each other

### ISSUE THREAD

**Issue by Andygol** [JOSM/turnlanes-tagging#11]
There is a lot of space between signs. Is it possible to put up signs tighter?
![image](https://cloud.githubusercontent.com/assets/369696/15856340/85b59e04-2cbd-11e6-91b9-486a08c5bb9c.png)

**Comment by Rub21** [comment]
@Andygol  do you think we still need to put more closer the icons?
![image](https://cloud.githubusercontent.com/assets/1152236/15944499/83da3102-2e53-11e6-8f0b-8c77b2f665bb.png)

**Comment by Rub21** [comment]
done!
