### ISSUE TITLE
Boton OK activo por default para dale enter y una observación en la seccion de historial

### ISSUE THREAD

**Issue by RichRico** [JOSM/turnlanes-tagging#12]
@Rub21 
##### Sería bueno dejarlo por default el boton OK para darle enter enseguida

![tag01](https://cloud.githubusercontent.com/assets/8484029/15875654/b9d3fb16-2cce-11e6-89ab-05979262f5e6.png)
##### También hay una observacion en la parte del historia.

![tag22](https://cloud.githubusercontent.com/assets/8484029/15876710/a6001f42-2cd4-11e6-835e-fa4ba54143af.png)

**Comment by Rub21** [comment]
done!
