### ISSUE TITLE
merge_to_right in the midle of way

### ISSUE THREAD

**Issue by Rub21** [JOSM/turnlanes-tagging#14]
@Andygol  The plugin does not support in this case, because there is a sign which  is `merge_to_right` in the midle lane, accoding here https://github.com/mapbox/turnlanes-tagging/issues/4#issuecomment-224253063 , in midle lanes does not exist `merge_to_right` and `merge_to_left`

Or maybe the solution is trace other way next to https://www.openstreetmap.org/way/392780047/history?

https://www.openstreetmap.org/way/392780047/history
![image](https://cloud.githubusercontent.com/assets/1152236/15912603/f6296c46-2d9a-11e6-8d00-6af0bafa0055.png)

cc @ediyes @RichRico

**Comment by Andygol** [comment]
@Rub21 IMO there is should be next tagging of such cases - https://www.openstreetmap.org/#map=18/37.811995/-121.300861
![lane-tagging](https://cloud.githubusercontent.com/assets/369696/15928616/98bb1ecc-2e50-11e6-99a9-ea6d792eead4.gif)

As you can see in the picture, there are two options: it is to draw a separate lane and mark the prohibition of movement on a particular lane

A similar case, a little north from this ☝️ intersection
https://www.openstreetmap.org/way/392822577

@planemad @abhisheksaikia @jothirnadh could you take a look 👀

**Comment by Andygol** [comment]
I hope that this problem is not common and it can be solved correcting tagging manually

**Comment by karitotp** [comment]
I think in the first option is not necessary to draw a separate lane because there is not physical separation, as you say maybe we can manually label these cases.

@Andygol @Rub21

**Comment by jothirnadh** [comment]
@karitotp I completely accept with you, if there is no physical separation we don't need to draw a new road link.

cc:/ @Andygol

**Comment by Rub21** [comment]
@Andygol @karitotp @jothirnadh :

What is the conclusion here?  i think Andy's solution is right, also is according the draft https://github.com/mapbox/turnlanes-tagging/issues/4#issuecomment-224253063 ,and supported by the plugin.  where said in the middle lane does not exit `merge_to_right`.

what do you think @jothirnadh @karitotp ?

**Comment by Rub21** [comment]
no actions here, we will continue with the Andy's suggestion.
