### ISSUE TITLE
The interface for bidirectional roads is wrong

### ISSUE THREAD

**Issue by jothirnadh** [JOSM/turnlanes-tagging#16]
While tagging a backward lane in bidirectional roads the interface is showing wrong lane markings.

![turn_lanes_plugin](https://cloud.githubusercontent.com/assets/8401827/16003889/9d83ea04-317c-11e6-8609-3e32c13c07a5.gif)

In the above GIF the turn lanes are present on the backward direction of the road. When we try to add the turn lanes, instead of `turn:lanes:backward=left||` it adds `turn:lanes:backward=right||`

![screen shot 2016-06-13 at 3 37 18 pm](https://cloud.githubusercontent.com/assets/8401827/16003986/06b3a9ba-317d-11e6-84e0-f907f120fc80.png)

_This should be the ideal interface, but now the plugin is taking the opposite turn lanes_

cc:/ @Rub21 @abhisheksaikia @planemad @Andygol

**Comment by Andygol** [comment]
@Rub21 
I just want to clarify an interface. As we count lanes from the center line It would be great if you change the order of lanes from the center to the edges
<img width="801" alt="turn lanes editor 2016-06-13 17-19-51" src="https://cloud.githubusercontent.com/assets/369696/16010740/39cdfd42-318b-11e6-8472-153bf9068fbe.png">

**Comment by Rub21** [comment]
done! release for the next version
