### ISSUE TITLE
Evento de scrolll en el spinner de lanes 

### ISSUE THREAD

**Issue by ridixcr** [JOSM/turnlanes-tagging#17]
Ruben Por favor  agrégale el evento de scroll en el spinner para que no dependamos de los clic y teclas direccionales para aumentar o disminuir el numero de lanes.
![Spinner de Lanes](https://cloud.githubusercontent.com/assets/1646072/16014197/d55ddff6-3155-11e6-85ef-7f7394481080.png)

Así facilitarías mucho mas el uso :pray:

**Comment by Rub21** [comment]
done
