### ISSUE TITLE
Agregar etiquetas de `lanes` y `turn:lanes` a más de una calle seleccionada

### ISSUE THREAD

**Issue by karitotp** [JOSM/turnlanes-tagging#22]
@Rub21 para asignar más rápido los turn lanes, cuando hay dos calles que tienen el mismo número de lanes y la misma señalización:
![turn](https://cloud.githubusercontent.com/assets/11504548/16025594/e367d8d0-318d-11e6-8fdc-be6ed7d22ee2.png)
Selecciono ambas calles y le asigno las etiquetas; sin embargo al hacer esto con el plugin las etiquetas de una de las calles se modifica.
![turn1](https://cloud.githubusercontent.com/assets/11504548/16025612/08f49cfa-318e-11e6-8a5b-fe3fcd447089.png)

Es posible que el plugin agregue solo las etiquetas de `lanes` y `turn:lanes`?

**Comment by Rub21** [comment]
por el momento se puede agregar en un segmento de calle! done here
