### ISSUE TITLE
move to https://github.com/JOSM/

### ISSUE THREAD

**Issue by Rub21** [JOSM/turnlanes-tagging#24]
hey @don-vip, Could you help me to move  turnlanes-tagging under /JOSM like https://github.com/JOSM/tofix-plugin

Thanks.

**Comment by don-vip** [comment]
Sure! I think you should be able to transfer it to @JOSM/turnlanes-tagging team now

**Comment by Rub21** [comment]
Thank you @don-vip ,  close here the ticket.

**Comment by Rub21** [comment]
@don-vip  Could you give me more permission to add more collaborators for this repository?

**Comment by don-vip** [comment]
Done :) https://github.com/orgs/JOSM/teams/turnlanes-tagging/repositories
