### ISSUE TITLE
Orden del forward y backward y funcionalidad del boton OK

### ISSUE THREAD

**Issue by RichRico** [JOSM/turnlanes-tagging#30]
@Rub21 
- Este orden de posición del forward y backward seria lo mas adecuado para paises con el sentido del transito por el lado derecho, ya que siempre nos enfocamos en el lado derecho para poder agregar los turn lanes.

![b](https://cloud.githubusercontent.com/assets/8484029/16248031/68cf1ad4-37d2-11e6-9521-a3356b3457b7.png)
- Este orden de posición de forward y backward seria mas adecuado para paises con el sentido del tránsito por el lado izquierdo, ya que ellos se enfocan mas en el lado izquierdo para poder agregar los turn lanes. 

![a](https://cloud.githubusercontent.com/assets/8484029/16248032/68d05cbe-37d2-11e6-9dfd-875468bdccc5.png)
- Para esto seria bueno que al momento de seleccionar el orden que deseamos se mantenga las posiciones del forward y backward, esto facilitará a añadir más rapido los turn lanes.
- Seria bueno tambíen que el boton OK se actibe cuando precionemos la tecla Enter.

**Comment by Rub21** [comment]
@RichRico  he solucionado  sobre la posiciones de backward and fordward, pero aun esta pendiendte. sobre `funcionalidad del boton OK`.  estare investigando mas sobre este punto.
