### ISSUE TITLE
Option to choose between `none` and empty values 

### ISSUE THREAD

**Issue by Andygol** [JOSM/turnlanes-tagging#32]
According to wiki empty value is shorthand for the value `none`. It would be nice to give users the choice of which option to use. 

_based on discussion on OSM-forum - http://forum.openstreetmap.org/viewtopic.php?pid=597879#p597879_

**Comment by Rub21** [comment]
done ! "none" was added as an option 
![image](https://cloud.githubusercontent.com/assets/1152236/16595681/150c5c56-42b6-11e6-9652-34e8db693857.png)
