### ISSUE TITLE
Different color for key templates

### ISSUE THREAD

**Issue by BushmanK** [JOSM/turnlanes-tagging#33]
In lower grid pane, where full list of existing tags and template keys is displayed, it would be a bit more convenient to have template keys (those which aren't added yet) in other color than black. Otherwise they are a kind of mixed with existing ones. 

Another option is to add thicker horizontal grid line between the existing tags and template keys.

**Comment by Andygol** [comment]
@BushmanK do you mean this 👇 ?
<img width="757" alt="turn lanes editor 2016-06-28 12-26-42" src="https://cloud.githubusercontent.com/assets/369696/16410561/bd322d60-3d2b-11e6-97dd-9cc99a535316.png">

**Comment by BushmanK** [comment]
@Andygol Yes, exactly. I don't know which grid formatting features Java UI framework used in JOSM actually supports, therefore, I'm just saying that these two things will look more intuitively, if separated  visually.

**Comment by Rub21** [comment]
I've fixed the issues here 
![image](https://cloud.githubusercontent.com/assets/1152236/16570148/aa50f1b6-4205-11e6-8612-a31f2e33fff4.png)
