### ISSUE TITLE
left an right hand traffic

### ISSUE THREAD

**Issue by Klumbumbus** [JOSM/turnlanes-tagging#34]
Maybe this is related to #30 but I don't understand the spanish.

It seems the interface is made for lefthandtraffic.
As you can see in the screenshot it is confusing. If backward is left and forward is right it would fit better.
(Actually it is a bit more complicated then just to switch the sides because the lanes count always from left to right in driving direction and not from center to side (if I'm corret), which made it all different for left hand traffic than for right hand traffic for bidirectional ways.)

JOSM has an [built-in database of areas with lefthandtraffic](https://josm.openstreetmap.de/wiki/left-right-hand-traffic). This could be used to determine if the selected road has left or righthandtraffic and the interface could be respectively adapted.

![turnlanestagging](https://cloud.githubusercontent.com/assets/7115609/16394039/92f4f33e-3cb3-11e6-89d0-420c48b33be6.png)

**Comment by Rub21** [comment]
@Klumbumbus 
 I've fixed  the problems using  [lefthandtraffic](https://josm.openstreetmap.de/wiki/left-right-hand-traffic) that was really helpful. 

now the plugin is setting up the forward and backward by country.

### Lefthand traffic

![image](https://cloud.githubusercontent.com/assets/1152236/16570047/b58a2126-4203-11e6-9336-17438b8ce5d2.png)

### Righthand traffic

![image](https://cloud.githubusercontent.com/assets/1152236/16570029/8d927e66-4203-11e6-8669-4104f1535081.png)

**Comment by Klumbumbus** [comment]
Thanks for your work on improving this plugin!
