### ISSUE TITLE
wrong order for `:backward` values

### ISSUE THREAD

**Issue by Andygol** [JOSM/turnlanes-tagging#35]
If **:backward** is on right side (by default) there is messed up left and right direction

<img width="1076" alt="turn lanes editor 2016-06-28 11-59-10" src="https://cloud.githubusercontent.com/assets/369696/16409902/8be7e496-3d28-11e6-9b94-631d7f63f22d.png">

**Comment by Rub21** [comment]
@Andygol  could you check the latest version, it is already on the JOSM list of plugins,  you only need to update it.

**Comment by Andygol** [comment]
@Rub21 
At first my glimpse all looks good 👍 

So, no next action - Closed
