### ISSUE TITLE
Sentido de las flechas es confuso

### ISSUE THREAD

**Issue by RichRico** [JOSM/turnlanes-tagging#36]
@Rub21 
El sentido de las flechas que indica en una bidireccional está mal, porque de acuerdo a las imágenes y el estilo dado en la calle no cuenciden con el orden de las flechas en el backward del plugin. 
aquí dejo una imagen.

![s](https://cloud.githubusercontent.com/assets/8484029/16434555/41872bfe-3d56-11e6-9233-09b90a5d352c.png)

segn la imagen, la flechas de la calle se abren, en cambion en el plugin se estan uniendo las flechas, y para hacer las señalizaciones es un poco confuso, seria bueno corregirlo, y tambien seía bueno considerar los ordenes que se indica aquí https://github.com/JOSM/turnlanes-tagging/issues/30

**Comment by Rub21** [comment]
arreglado en la nueva version!
