### ISSUE TITLE
Wrong init exists tag turn:lanes:*

### ISSUE THREAD

**Issue by freeExec** [JOSM/turnlanes-tagging#43]
The original tag `turn:lanes:backward=left;through|through`.
Then, when I open the plugin, the tag is not correct `turn:lanes:forward`

Test way 
![tunrline-tag-bug1](https://cloud.githubusercontent.com/assets/2344223/16626354/872bd68c-43b9-11e6-8fda-a0c0abf3c0f9.png)

**Comment by Klumbumbus** [comment]
I noticed this too.

**Comment by Rub21** [comment]
thank you for notice this error, I fixed the plugin!
