### ISSUE TITLE
Adapt graphical way display from old deprecated JOSM plugin "turnlanes".

### ISSUE THREAD

**Issue by stephan75** [JOSM/turnlanes-tagging#44]
The **old and deprecated** JOSM plugin linked at https://wiki.openstreetmap.org/wiki/Relations/Proposed/turn_lanes#Plugin was based on OSM relations, and that tagging method is no more popular any more.

But IMHO this plugin has a very beautiful display of the ways and streets that have turn lanes. Ways are drawn how they are really structured in rendered OSM data!

So how much effort would it be to **adapt only these graphical methods** to display turnlanes via the more used and popular tags that are simply added to each way without those relations?

Is this possible from sourcecode at all?

**Comment by stephan75** [comment]
So here you can see an example GUI screenshot of that JOSM plugin:

![image](https://cloud.githubusercontent.com/assets/5250044/17412650/22deaf3e-5a7e-11e6-980c-40cadded00dd.png)

Unfortunately I have no coding skills for that aim ... maybe anyone can help?

**Comment by Klumbumbus** [comment]
Why not simply use the Lane and Road Attributes mappaint style? As there is now an auto update (https://github.com/JOSM/turnlanes-tagging/issues/51#issuecomment-237611057) you directly get the visual result.

**Comment by stephan75** [comment]
Ohhh , I didn't know that feature ...

Although using JOSM  10733 and turnlanes-tagging (1468266519) I am NOT able to see this direct effect on JOSM map paint.

What am I doing wrong?

**Comment by samely** [comment]
@stephan75 
That's true. You can use the preview functionality. And you're doing nothing wrong, I've just updated the plugin, so in an hour you can update the plugin in your JOSM. If you still have any doubt, just reopen the ticket. Thanks!
