### ISSUE TITLE
No detecta automáticamente el tag de turnlanes de backward y forward  

### ISSUE THREAD

**Issue by ridixcr** [JOSM/turnlanes-tagging#46]
![Cap1](https://cloud.githubusercontent.com/assets/1646072/16660651/f337e624-4434-11e6-9215-5a269173714f.png)
##### Abrimos el Plugin turnlanes-tagging

![Cap2](https://cloud.githubusercontent.com/assets/1646072/16660806/8d2afd34-4435-11e6-9c75-b7ab54d48dbc.png)
##### No detecta automáticamente el tag de turnlanes según el sentido de  la calle

![Cap3](https://cloud.githubusercontent.com/assets/1646072/16660653/f3457a00-4434-11e6-8114-eb44b288afb1.png)
##### Como resultado se obtiene un taggeo incorrecto

![Cap4](https://cloud.githubusercontent.com/assets/1646072/16660812/97007974-4435-11e6-8725-6803d0331a18.png)

**Comment by Rub21** [comment]
@ridixc esto ya fue solucionado!
