### ISSUE TITLE
Ability to preview the results without pressing Enter

### ISSUE THREAD

**Issue by baditaflorin** [JOSM/turnlanes-tagging#51]
Now, i try something, i save and see if i got the right result. 

If not, i have to open the plugin again, change something and try again. 

It would be great if it`s possible to show in real-time how the end result will look.

**Comment by Andygol** [comment]
@Rub21 
maybe it would be possible reuse such behaviour from `Tag multiple objects (alpha)` from [`UtilsPlugin2`](https://josm.openstreetmap.de/wiki/Help/Plugin/UtilsPlugin2) 

<img width="309" alt="data 2016-07-20 14-23-29" src="https://cloud.githubusercontent.com/assets/369696/16984999/54ce008e-4e86-11e6-8680-f45c8d717190.png">

**Comment by Andygol** [comment]
**Tag multiple objects** (demo)

![cmd_t](https://cloud.githubusercontent.com/assets/369696/16985117/282ea32a-4e87-11e6-84c5-a28f360a3f4d.gif)

**Comment by Rub21** [comment]
@baditaflorin @Andygol , That is a good idea, let me try if we can add that functionality.

**Comment by samely** [comment]
@Rub21 I continued your progress for this functionality and have fixed the undo-redo issue. Now preview is available.

![anim](https://cloud.githubusercontent.com/assets/10425629/17410149/176623a8-5a38-11e6-815a-9f6764a3f336.gif)

cc .- @baditaflorin @Andygol
