### ISSUE TITLE
Suggest to people to activate the Draw Direction Arrows

### ISSUE THREAD

**Issue by baditaflorin** [JOSM/turnlanes-tagging#52]
This will allow for faster observance of the direction of the way. 

http://i.imgur.com/QNxN1md.gif
![qnxn1md](https://cloud.githubusercontent.com/assets/369696/16984348/07d744c4-4e82-11e6-90bb-4faae9462d84.gif)

**Comment by Andygol** [comment]
@baditaflorin 
Does it really necessary? When we select particular way we are able to see its direction. 
![ways_arrows](https://cloud.githubusercontent.com/assets/369696/16984585/94554b70-4e83-11e6-8528-e22e2aef3f5e.gif)

**Comment by Klumbumbus** [comment]
> When we select particular way we are able to see its direction. 

For me that's also sufficient. I don't use the always displayed direction arrows because to me they are annoying.
However this is just my personal opinion

**Comment by samely** [comment]
This idea will be considered when the page for wiki is ready.
