### ISSUE TITLE
`Preset` and `tag` do not match in bidirectional mode

### ISSUE THREAD

**Issue by abhisheksaikia** [JOSM/turnlanes-tagging#53]
There is a mismatch between the `preset` and the `tags`. For e.g.: If we select `forward: backward: left|`, the turn lane tagged is actually `turn:lanes:forward=left|`

![screen shot 2016-07-26 at 6 10 19 pm](https://cloud.githubusercontent.com/assets/13744156/17138353/7f9af2c8-535d-11e6-8e22-e372a2c86172.png)

It also changes the lane count accordingly leading to errors in lane counts in forward and backward direction

cc @Rub21

**Comment by samely** [comment]
@abhisheksaikia I've already fixed this.
![image](https://cloud.githubusercontent.com/assets/10425629/17417594/bc3c378e-5a59-11e6-8740-08291a548433.png)

cc. @Rub21
