### ISSUE TITLE
Errores detectados y sugerencias.

### ISSUE THREAD

**Issue by RichRico** [JOSM/turnlanes-tagging#54]
@Rub21 @samely 
- [x] El plugin debería autodetectar si la carretera es unidireccional o bidireccional 
- [x] La cola de historial sea rotativo e incrmental
- [x] El evento de spiners de linea sean agregados en los paneles de señalizacion.
- [x] El numero de lanes en la señalización de unidireccional no coincide para `lanes=1`.
- [x] Los valores del historial no debería ser repetitivo.
- [x] El historial no guarda valores de reverse
- [x] Al deseleccionar la calle a editar el boton cancelar del plugin manda un error
- [x] Sería bueno que el botón OK se active al precionar la tecla ENTER.

**Comment by samely** [comment]
He solucionado algunas cosas del plugin y además agregué algunas funcionalidades sugeridas.
