### ISSUE TITLE
turnlanes tagging plugin does not become "inactive" which results in a NPE

### ISSUE THREAD

**Issue by Klumbumbus** [JOSM/turnlanes-tagging#56]
complete description see https://josm.openstreetmap.de/ticket/13133

**Comment by samely** [comment]
I've tried and seems to work well. 
Can you provide more details, please?
![anim](https://cloud.githubusercontent.com/assets/10425629/17602917/61045c40-5fd4-11e6-9c4b-d604ba1cb0da.gif)

**Comment by Klumbumbus** [comment]
you need to keep the way selected before deleting the layer

**Comment by samely** [comment]
Thanks @Klumbumbus I've already fixed it.
