### ISSUE TITLE
Should not define lanes and lanes:* by default

### ISSUE THREAD

**Issue by naoliv** [JOSM/turnlanes-tagging#67]
Have a way with any of these tags:
- `highway=residential`
- `highway=residential` + `oneway=no`
- `highway=residential` + `oneway=no` + `lanes=2`

Select it and open the plugin
We can see this:

![](https://cloud.githubusercontent.com/assets/982338/18103571/9b272530-6ecd-11e6-966f-9d673b5d3b98.png)

It should not set any default value for `lanes`, `lanes:forward` and `lanes:backward` but let the user select first the road characteristics (uni/bidirectional, number of lanes, etc) and only then allow to select the lanes directions.

**Comment by samely** [comment]
@naoliv  I've already fixed this issue. You can upload the plugin. Thanks for your feedback.
